### PR TITLE
Reconfigure video2dataset swiss_ai settings for the todi cluster

### LINKED ISSUE #7: Download data to todi in video2dataset format.
Download **HowTo100M** and **Hd-vila** datasets in video2dataset format using the scripts/methods described in https://github.com/swiss-ai/video2dataset/tree/main/swiss_ai.

This will be downloaded in this format:
```
 ├── 00000.tar
 |     ├── 00000.mp4
 |     ├── 00000.txt
 |     ├── 00000.json
 |     ├── 00001.mp4
 |     ├── 00001.txt
 |     ├── 00001.json
 |     └── ...
 |     ├── 10000.mp4
 |     ├── 10000.txt
 |     ├── 10000.json
 ├── 00001.tar
 |     ├── 10001.mp4
 |     ├── 10001.txt
 |     ├── 10001.json
 │     ...
 ...
```
Child issue of #3.

### PR DESCRIPTION
**Pull request by kdu4108**
### Summary
To download videos onto the todi cluster with video2dataset using slurm, we need to configure some specific settings.
This PR includes:
* the `download_todi.config`, which defines parameters to use for using slurm to execute video2dataset in parallel on many videos.
* updates to the commands you need to run to download howto100m and hdvila (NOT moments in time yet) in [swiss_ai/datasets/HowTo100M.md](https://github.com/swiss-ai/video2dataset/compare/main...swiss-ai:video2dataset:kdu/todi?expand=1#diff-8da0a1652a05c54e93eea5a4e14e5cc478837b2e9a23add8279c67f73f10dd7c) and [swiss_ai/datasets/HDVILA.md](https://github.com/swiss-ai/video2dataset/compare/main...swiss-ai:video2dataset:kdu/todi?expand=1#diff-b3e5c4ff774e331eb03256c835bd8bcb27dcedb92195ebc37d38874ac42a71b8).
* removing `decord` from requirements.txt because that needs to be installed from source on the GH200 arm processors (see https://github.com/swiss-ai/containers/blob/main/v2d/Dockerfile for where this is done).
* modifying the `distributor.py` file to include an environment variable (for which image to build the container with on todi) and a timeout variable.

I also did some quick tests on downloading small amounts of data of howto100m with different variations of num_tasks_per_node and num_cpus_per_task, detailed in the comments in the download_todi config file.

### Test strategy
1. [DONE] Ran `video2dataset --url_list="/store/swissai/a08/data/raw/howto100m/v2d/howto100m_v2d_0_1000.csv" --config="/store/swissai/a08/kdu/video2dataset/swiss_ai/configs/download_todi.yaml" --output_folder="/store/swissai/a08/data/raw/howto100m/v2d" --input_format="csv" --output_format="webdataset" --url_col="video_link" --encode_formats="{'video': 'mp4', 'audio':'m4a'}"` within a container started with `srun --overlap --jobid=<JOBID> --environment=v2d --container-workdir=$PWD --pty bash` to confirm that the data can be downloaded.
2. [TODO] Run `video2dataset --url_list="/store/swissai/a08/data/raw/howto100m/v2d_40k/howto100m
_v2d_0_40000.csv" --config="/store/swissai/a08/kdu/video2dataset/swiss_ai/configs/download_todi.yaml" --output_folder="/store/swissai/a08/data/raw/howto100m/v2d_40k" --input_format="csv" --output_format="webdataset" --url_col="vid
eo_link" --encode_formats="{'video': 'mp4', 'audio':'m4a'}"` (expected to finish in about 4 hours, the max time limit of a slurm job.). Job ID = 39836
3. [TODO] Run `srun --overlap --jobid=<JOBID> --environment=v2d --container-workdir=$PWD video2dataset --url_list="/store/swissai/a08/data/raw/howto100m/v2d/howto100m_v2d.csv" --config="/store/swissai/a08/containers/v2d/video2dataset/swiss_ai/configs/download_todi.yaml" --output_folder="/store/swissai/a08/data/raw/howto100m/v2d" --input_format="csv" --output_format="webdataset" --url_col="video_link" --encode_formats="{'video': 'mp4', 'audio':'m4a'}"` to download the full howto100m dataset.
4. [TODO] Run `srun --overlap --jobid=<JOBID> --environment=v2d --container-workdir=$PWD video2dataset --url_list="/store/swissai/a08/data/raw/hdvila/hd_vila.parquet" --config="/store/swissai/a08/containers/v2d/video2dataset/swiss_ai/configs/download_todi.yaml" --output_folder="/store/swissai/a08/data/raw/hdvila/hd_vila_v2d" --input_format="parquet" --output_format="webdataset" --url_col="url" --encode_formats="{'video': 'mp4', 'audio':'m4a'}"` to download the full hdvila dataset.

### CODE REVIEW

**Comment by markus583** [comment]
Have you tested unpacking any of the resulting tar files? Are they ok?

**Comment by kdu4108** [comment]
Added some new commits for fixing the timeout error. Basically SlurmDistributor has a timeout function too, but since todi will take the timeout from #SBATCH time={self.timeout} we should make sure SlurmDistributor doesn't accidentally kill the job early by setting its timeout threshold to 2 weeks.

**Comment by kdu4108** [comment]
> Have you tested unpacking any of the resulting tar files? Are they ok?

Yes, by doing `tar -xvf 0000000007.tar` it seems to unpack the m4a and mp4s! And in vscode I could play one of the mp4s so I think we're good :)

**Review by markus583 — APPROVED** [review]

**Comment by kdu4108** [comment]
Cross link with this issue: https://github.com/swiss-ai/ml-4m/issues/7

**Comment by kdu4108** [comment]
Going to merge early (before running the full data downloads) because other v2d branches (e.g. whisper) will benefit from the todi configs and the timeout fixes.

Next steps:
1) Hold off on the full data download until we have the full pipeline working. Instead, temporarily work with the smaller data downloads. 
2) When pipeline is validated, move the smaller data downloads into a `data/toy/` directory and do the full data download.

**Pull request merged**
